openapi: 3.0.0
info:
  title: Microservice Wallet
  version: 1.0.0
  
servers:
  - url: http://localhost:3001
    description: Local
  
  
tags:
  - name: Transactions

paths:
  # Transactions
  /transactions:
    post:
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transactions'
      tags:
        - Transactions
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsModel'
          description: Response
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          $ref: '#/components/responses/ConflictError'
      security: 
        - bearerAuth: []
    get:
      tags:
        - Transactions
      security: 
        - bearerAuth: []
      parameters:
        - in: query
          name: type
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionsModel'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  # Transactions
  /balance:
    get:
      description: Esse endpoint deve retornar um consolidado das transações de CREDITO e DEBITO, fazendo o calculo do valor, de prefência que seja uma query fazendo o calculo
      tags:
        - Transactions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security: 
        - bearerAuth: []
components:
  schemas:
    Transactions:
      type: object
      required:
      - type
      - amount
      properties:
        amount:
          type: number
        type:
          type: string
          enum:
          - CREDIT
          - DEBIT
    TransactionsModel:
      type: object
      required:
      - user_id
      - type
      - amount
      - created_at
      properties:
        id: 
          type: string
        user_id:
          type: string
        amount:
          type: number
        type:
          type: string
          enum:
          - CREDIT
          - DEBIT
        created_at:
          type: string
    BalanceResponse:
      type: object
      properties:
        amount:
          type: number
        
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid    
    BadRequestError:
      description: Invalid request
    ConflictError:
      description: Request conflict