openapi: 3.0.0
info:
  title: Microservice Users
  version: 1.0.0
  
servers:
  - url: http://localhost:3002
    description: Local
  
  
tags:
  - name: Users
  - name: Auth

paths:
  # Users
  /users:
    post:
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      tags:
        - Users
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
          description: Response
        '400':
          $ref: '#/components/responses/BadRequestError'
        '409':
          $ref: '#/components/responses/ConflictError'
      
    get:
      tags:
        - Users
      security: 
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsersResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/me:
    patch:
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      tags:
        - Users
      security: 
        - bearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
          description: Response
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
      
    get:
      tags:
        - Users
      security: 
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    delete:
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      tags:
        - Users
      security: 
        - bearerAuth: []
      responses:
        204:
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
  
  # Auth
  /auth:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      tags:
        - Auth
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Response
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    
  
components:
  schemas:
    UserRequest:
      type: object
      required:
      - first_name
      - last_name
      - password
      - email
      properties:
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
        email:
          type: string
    Users:
      type: object
      required:
      - id
      - first_name
      - last_name
      - password
      - email
      properties:
        id: 
          type: string
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
        email:
          type: string
    UsersModel:
      type: object
      required:
      - id
      - first_name
      - last_name
      - password
      - email
      properties:
        id: 
          type: string
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
        email:
          type: string
    UsersResponse:
      type: object
      required:
      - id
      - first_name
      - last_name
      - email
      properties:
        id: 
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
    AuthRequest:
      type: object
      required:
      - email
      - password
      properties:
        user: 
          type: object
          properties:
            email: 
              type: string
            password:
              type: string

    AuthResponse:
      type: object
      required:
      - email
      - password
      properties:
        user: 
          type: object
          properties:
            id: 
              type: string
            first_name:
              type: string
            last_name:
              type: string
            email:
              type: string
        access_token:
          type: string
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid    
    BadRequestError:
      description: Invalid request
    ConflictError:
      description: Request conflict
    NotFoundError:
      description: Resource not found
